# Generated by Django 6.0.5 on 2026-05-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=20)),
                ('deadline', models.DateField(blank=True, max_length=100, null=True, verbose_name='Срок выполнения')),
            ],
            options={
                'verbose_name': 'Задание',
                'db_table': 'Задания',
            },
        ),
    ]
